// Catégories partagées entre saisie manuelle, vocale, produits, import IA.
// Volontairement large pour couvrir tous types de petites activités.
export const CATEGORIES = [
  // Alimentation & Boissons
  "Boissons",
  "Boissons alcoolisées",
  "Sucreries",
  "Eau minérale",
  "Café / Thé",
  "Restauration",
  "Plats préparés",
  "Petit-déjeuner",
  "Snacks / Grignotage",
  "Fast-food",
  "Pâtisserie",
  "Boulangerie",
  "Viandes",
  "Volaille",
  "Poissons",
  "Fruits de mer",
  "Legumes",
  "Fruits",
  "Condiments / Épices",
  "Alimentation générale",
  "Céréales / Riz",
  "Huiles",
  "Produits laitiers",
  "Œufs",
  // Vie courante
  "Hygiène",
  "Cosmétique / Beauté",
  "Parfumerie",
  "Coiffure",
  "Habillement",
  "Chaussures",
  "Accessoires / Bijoux",
  "Textile",
  "Papeterie",
  "Livres / Éducation",
  "Jouets",
  "Cadeaux",
  // Maison
  "Électroménager",
  "Meubles",
  "Décoration",
  "Vaisselle / Cuisine",
  "Literie",
  "Quincaillerie",
  "Matériaux BTP",
  "Peinture",
  "Outillage",
  // Techno
  "Téléphones",
  "Accessoires téléphone",
  "Informatique",
  "Électronique",
  "Logiciels / Abonnements",
  "Internet / Wi-Fi",
  "Crédit téléphone",
  // Services
  "Services",
  "Réparation",
  "Nettoyage",
  "Sécurité",
  "Publicité / Marketing",
  "Événementiel",
  "Photographie / Vidéo",
  "Location",
  "Formation",
  // Transport & Énergie
  "Carburant",
  "Transport",
  "Livraison",
  "Péage / Parking",
  "Entretien véhicule",
  "Pièces détachées",
  // Charges / Admin
  "Loyer",
  "Électricité",
  "Eau",
  "Gaz",
  "Assurance",
  "Impôts / Taxes",
  "Frais bancaires",
  "Transferts Mobile Money",
  "Frais Wave / MTN / Orange / Moov",
  "Salaires",
  "Charges sociales (CNPS)",
  "Fournisseurs",
  "Emballage",
  // Santé
  "Santé",
  "Pharmacie",
  "Consultation médicale",
  "Analyses / Examens",
  // Agriculture / Élevage
  "Semences / Intrants",
  "Engrais",
  "Aliments bétail",
  "Aliments volaille",
  "Vétérinaire",
  // Finance
  "Épargne",
  "Prêt / Crédit reçu",
  "Remboursement prêt",
  "Investissement",
  "Tontine",
  "Don / Aide",
  // Divers
  "Réception client",
  "Perte / Casse",
  "Vol / Manquant",
  "Divers",
  "Autre",
];

export const PAIEMENTS = [
  "Espèces",
  "Wave",
  "MTN Money",
  "Orange Money",
  "Moov Money",
  "Djamo",
  "Carte bancaire",
  "Virement",
  "Chèque",
  "Crédit client",
  "À crédit",
];