/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoixRouteImport } from './routes/_authenticated/voix'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedSynchronisationRouteImport } from './routes/_authenticated/synchronisation'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedOperationsNewRouteImport } from './routes/_authenticated/operations.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoixRoute = AuthenticatedVoixRouteImport.update({
  id: '/voix',
  path: '/voix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSynchronisationRoute =
  AuthenticatedSynchronisationRouteImport.update({
    id: '/synchronisation',
    path: '/synchronisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsNewRoute =
  AuthenticatedOperationsNewRouteImport.update({
    id: '/operations/new',
    path: '/operations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/import': typeof AuthenticatedImportRoute
  '/synchronisation': typeof AuthenticatedSynchronisationRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/voix': typeof AuthenticatedVoixRoute
  '/operations/new': typeof AuthenticatedOperationsNewRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/import': typeof AuthenticatedImportRoute
  '/synchronisation': typeof AuthenticatedSynchronisationRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/voix': typeof AuthenticatedVoixRoute
  '/operations/new': typeof AuthenticatedOperationsNewRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/synchronisation': typeof AuthenticatedSynchronisationRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/_authenticated/voix': typeof AuthenticatedVoixRoute
  '/_authenticated/operations/new': typeof AuthenticatedOperationsNewRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/historique'
    | '/import'
    | '/synchronisation'
    | '/utilisateurs'
    | '/voix'
    | '/operations/new'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/historique'
    | '/import'
    | '/synchronisation'
    | '/utilisateurs'
    | '/voix'
    | '/operations/new'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/historique'
    | '/_authenticated/import'
    | '/_authenticated/synchronisation'
    | '/_authenticated/utilisateurs'
    | '/_authenticated/voix'
    | '/_authenticated/operations/new'
    | '/_authenticated/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voix': {
      id: '/_authenticated/voix'
      path: '/voix'
      fullPath: '/voix'
      preLoaderRoute: typeof AuthenticatedVoixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/synchronisation': {
      id: '/_authenticated/synchronisation'
      path: '/synchronisation'
      fullPath: '/synchronisation'
      preLoaderRoute: typeof AuthenticatedSynchronisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/new': {
      id: '/_authenticated/operations/new'
      path: '/operations/new'
      fullPath: '/operations/new'
      preLoaderRoute: typeof AuthenticatedOperationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedSynchronisationRoute: typeof AuthenticatedSynchronisationRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
  AuthenticatedVoixRoute: typeof AuthenticatedVoixRoute
  AuthenticatedOperationsNewRoute: typeof AuthenticatedOperationsNewRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedSynchronisationRoute: AuthenticatedSynchronisationRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
  AuthenticatedVoixRoute: AuthenticatedVoixRoute,
  AuthenticatedOperationsNewRoute: AuthenticatedOperationsNewRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
